language: node_js
node_js:
  - lts/*
install:
  - npm ci
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:cov
after_success: npm run test:cov:report
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
