version: '3.9'

services:
  server:
    container_name: clean-architecture-server
    build: docker/node
    image: clean-architecture-server
    command: /bin/bash
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "5555:5555"
    env_file: &env_file
      - .env
    depends_on:
      - database
  database:
    container_name: clean-architecture-database
    image: postgres:13-alpine
    healthcheck:
      test: ["CMD", "/opt/healthcheck/postgres"]
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker/healthcheck:/opt/healthcheck
    env_file: *env_file

volumes:
  postgres:
